spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASS}

debug: ${DEBUG_ENABLED:false}

logging:
  file:
    path: ${LOG_PATH:./logs}
    max-size: 10MB
    max-history: 10
    
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    disable-swagger-default-url: true
  
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:15m}
    

custom:
  property:
    cncf:
      url: https://landscape.cncf.io/data.json
    security:
      admin:
        username: ${RACI_ADMIN_USER}