#!/bin/bash

SERVER_PORT=$1
MYSQL_DB_NAME=$2
MYSQL_DB_USER=$3
MYSQL_DB_PASS=$4
RACI_ADMIN_USER=$5
LOG_PATH=$6
SWAGGER_ENABLED=$7
JAR_PATH=$8

java -DSERVER_PORT=$SERVER_PORT -DMYSQL_DB_NAME=$MYSQL_DB_NAME -DMYSQL_DB_USER=$MYSQL_DB_USER -DMYSQL_DB_PASS=$MYSQL_DB_PASS -DRACI_ADMIN_USER=$RACI_ADMIN_USER -DLOG_PATH=$LOG_PATH -DSWAGGER_ENABLED=$SWAGGER_ENABLED -jar $JAR_PATH &
